Models/ErrorViewModel.cs
namespace EncounterCreator.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ViewModels/MonsterViewModel.cs
using EncounterModels;

namespace EncounterCreator.ViewModels
{
    public class MonsterViewModel
    {
        public List<Monster> Monsters { get; set; }

    }
}

Controllers/EncounterController.cs
using EncounterCreator.ViewModels;
using EncounterInterfaces;
using EncounterModels;
using Microsoft.AspNetCore.Mvc;

namespace EncounterCreator.Controllers
{
    public class EncounterController : Controller
    {
        private readonly IEncounterService _encounterService;
        public EncounterResult Encounter { get; set; }

        public EncounterController(IEncounterService encounterService)
        {
            _encounterService = encounterService;
           
        }

        public IActionResult Index() { return View("GenerateEncounter"); }
        
        [HttpPost]
        public async Task<IActionResult> GenerateEncounter(int partySize, int playerLevel, string difficulty = "easy")
        {                 
            Encounter = await _encounterService.GenerateEncounter(partySize, playerLevel, difficulty);

           
            
            return View("GenerateEncounter",Encounter);

        }

        public async Task<List<Monster>> GetMonsterList() {
            List<Monster> monsterList = await _encounterService.GetMonsterList();
            return monsterList;
        }

       
    }
}

Controllers/HomeController.cs
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

public class HomeController : Controller
{

    public IActionResult Index() { return View(); }

}

Views/Encounter/GenerateEncounter.cshtml
@using System.Linq


<!DOCTYPE html>
<html>
<head>
    <title>Party</title>
    <link rel="stylesheet" src="~/css/encounter.css" type="text/css"/>
</head>
<body>
    <div class="main">
        <div class="left">
            <h1>Party</h1>
            <form class="encounter-form" method="post" action="@Url.Action("GenerateEncounter", "Encounter")">
                
                <div class="encounter-party">
                    <div class="encounter-input-group">
                        <label for="partySize">Players:</label>
                        <input type="number" name="partySize" id="partySize" required><br>
                    </div>
                    <div class="seperator">X</div>
                    <div class="encounter-input-group">
                        <label for="playerLevel">Level:</label>
                        <input type="number" name="playerLevel" id="playerLevel" required><br>

                    </div>
                </div>

                <div class="encounter-difficulty">
                    <select name="difficulty" id="difficulty">
                        <option value="easy">Easy</option>
                        <option value="medium">Medium</option>
                        <option value="hard">Hard</option>
                        <option value="deadly">Deadly</option>
                    </select>

                    <button type="submit">Generate Encounter</button>
                </div>

            </form>
            
            <div class="encounter-output">
                @if (Model?.Monsters != null && Model?.Monsters.Count > 0)
                {

                    var monsterQuantities = new Dictionary<string, int>();

                    <div class="encounter-summary">
                        <h2>EXP Goals</h2>
                        <ul class="encounter-exp">
                            @foreach (var xpSum in Model?.XpSums)
                            {
                                <li>@xpSum.Key: @xpSum.Value</li>
                            }
                        </ul>

                    </div>
                    <h1>Monsters List</h1>

                    <ul class="monster-list">

                        @foreach (var monster in Model.Monsters)
                        {
                            if (monsterQuantities.ContainsKey(monster.Name))
                            {
                                monsterQuantities[monster.Name]++;
                            }
                            else
                            {
                                monsterQuantities.Add(monster.Name, 1);
                            }


                            <div class="monster">
                                <div class="monster-details">
                                    <h6 class="monster-name">@monster.Name</h6>
                                    <p class="monster-type">@monster.Size @monster.Type</p>
                                </div>
                                <div class="monster-info">
                                    <p class="monster-cr-exp">CR: <span id="monster-cr">@monster.CR</span> | Exp: <span id="monster-exp">@monster.ExperiencePoints</span></p>
                                    <div class="monster-quantity">
                                        <button class="quantity-increase">+</button>
                                        <input type="number" class="quantity-input" value="@monsterQuantities[monster.Name]">
                                        <button class="quantity-decrease">-</button>
                                    </div>
                                </div>
                            </div>

                        }
                    </ul>
                <div>
                    
                        <p>Total Exp: <span id="exp-total">@Model.TotalExp</span></p>
                    <p>Adjusted Exp: @Model.AdjustedExp</p>
                </div>
                }

            </div>
        
        </div>
        <div class="center">
            <input type="text" id="search" onkeyup="Search()" placeholder="Search for names..">
            
            
            <table id="monster-table" class="table table-responsive table-striped table-dark">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col">Name</th>
                        <th scope="col">CR</th>
                        <th scope="col">Type</th>
                        <th scope="col">Size</th>
                    </tr>
                </thead>
                <tbody id="monster-list-body">
                    
                </tbody>
            </table>
            <div class="pagination">
                <button id="prev-page"> &larr; Previous</button>
                <ul id="pagination-list">

                </ul>
                <button id="next-page">Next &rarr;</button>
            </div>
        </div>

        <div class="right">

             <div class="row">
                 <h3>Size</h3>
                 <div class="filter-tags"></div>
                <select id="size-filter" class="form-select filter-input">
                    <option value="default" selected disabled hidden>Choose here</option>              
                    <option value="Tiny">Tiny</option>
                    <option value="Small">Small</option>
                    <option value="Medium">Medium</option>
                    <option value="Large">Large</option>
                    <option value="Gargantuan">Gargantuan</option>
          
                </select>
             </div>
           


        </div>

    </div>
    

</body>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="/js/Encounter.js"></script>
<script src="/js/MonsterTable.js"></script>
<script src="/js/MonsterTableFilters.js"></script>


</html>

Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Party</title>
</head>
<body>
   
    <div class="bg-dark text-secondary px-4 py-5 text-center">
        <div class="py-5">
            <img src="Assets/dragon.svg" class="img-fluid hero-image" />
            <h1 class="display-5 fw-bold text-white">Manifest</h1>
            <div class="col-lg-6 mx-auto">
                <p class="fs-5 mb-4">Manifest Your Adventure, One Monster at a Time.</p>
                <p>Monster Manifest is your portal to infinite possibilities within the realms of Dungeons and Dragons. Whether you're a seasoned Dungeon Master or a budding hero, our platform empowers you to craft, customize, and conquer the most memorable encounters in your D&D campaigns.</p>
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                    <button type="button" class="btn btn-outline-info btn-lg px-4 me-sm-3 fw-bold" fdprocessedid="9d9vf" onclick="location.href=`@Url.Action("Index", "Encounter")`">Manifest</button>
                </div>
            </div>
        </div>
    </div>
  
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EncounterCreator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EncounterCreator.styles.css" asp-append-version="true" />
</head>
<body class="bg-dark">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3" >
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="navbar-logo" src="/Assets/dragon.svg"/>Manifest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">
                        <span class="bar"></span>
                        <span class="bar"></span>
                        <span class="bar"></span>
                    </span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Encounter" asp-action="Index">Encounter</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>